on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "* 0/12 * * *"

name: Test

jobs:
  test-keys:
    name: Test keys
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Start test
        run: python test.py keys.txt -scj
